# travis rules for project
language: cpp
compiler:
  - gcc

before_install:
  # install deps
  - sudo apt-get install -y  libboost-system-dev  libopencv-dev

script: # compile
  - mkdir build
  - cd build
  - cmake ..
  - make
